### ISSUE TITLE
Nginx module referenced twice

### ISSUE THREAD

**Issue by franz-josef-kaiser** [yappabe/docker-nginx#5]
The `--with-http_realip_module` is referenced on [L#41](https://github.com/yappabe/docker-nginx/blob/efafbc5a4d5323457edee4d9c8bd3e39411c4622/1.9-pagespeed/Dockerfile#L41) and [L#55](https://github.com/yappabe/docker-nginx/blob/efafbc5a4d5323457edee4d9c8bd3e39411c4622/1.9-pagespeed/Dockerfile#L55).

Btw, nice build with the ngx pagespeed module.

**Comment by jverdeyen** [comment]
Can you PR to remove the line? 😊 thx!

**Comment by franz-josef-kaiser** [comment]
@jverdeyen done – pushed to `master` directly, added the `v1.1.1` tag. Sidenote: I'd remove the `v` in the beginning of the tags. It's not needed in some cases it makes problems even if it's considered to be semver compatible.

**Comment by franz-josef-kaiser** [comment]
The point where I normally add the `v` is when I add [Releases](https://github.com/yappabe/docker-nginx/releases) on GitHub. It looks nicer and serves as great download page, much prettier than the default tags. :)

**Comment by franz-josef-kaiser** [comment]
Ok, the tag didn't make it through the PR … GitHub. Here's the copy-pasta for it:

```
git tag -a "v1.1.1" 1915404 -m "Removes doubled HTTP real-IP module inclusion"
```
